name: gain_solutions_flutter_assignment
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  either_dart: ^1.0.0
  equatable: ^2.0.7
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.3
  get_it: ^8.0.3
  google_fonts: ^6.2.1
  go_router: ^14.8.1
  hydrated_bloc: ^9.1.5
  http: ^1.3.0
  internet_connection_checker: ^3.0.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  in_app_update: ^4.2.3
  package_info_plus: ^8.3.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_animate: ^4.5.2
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/mocks/
    - assets/icons/
